In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(11,)

In [7]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# note [[], [], []] -> 2d list

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
array2.shape

(3, 4)

In [10]:
array1.size

11

In [11]:
array2.size

12

In [12]:
array3 = np.full(6, 7)
print(array3)

[7 7 7 7 7 7]


In [13]:
array4 = np.zeros(6, dtype=int)
print(array4)

[0 0 0 0 0 0]


In [14]:
array5 = np.ones(6, dtype=int)
print(array5)

[1 1 1 1 1 1]


In [15]:
array6 = np.random.random(6)
print(array6)

[0.52923741 0.20463189 0.18700385 0.64433611 0.39695256 0.17182279]


In [16]:
array7 = np.arange(6)
print(array7)

[0 1 2 3 4 5]


In [17]:
array8 = np.arange(2, 7)
print(array8)

[2 3 4 5 6]


In [18]:
array9 = np.arange(2, 7, 2)
print(array9)

[2 4 6]


In [19]:
array10 = np.array([2, 3, 7, 8, 9])
print(array10[2])
print(array10[-1])
print(array10[2:4])
print(array10[0:5:2])
print()

print(array10[[0, 1, 3]])
array11 = np.array([0, 1, 3])
print(array10[array11])

7
9
[7 8]
[2 7 9]

[2 3 8]
[2 3 8]


In [20]:
array12 = np.arange(10)
print(array12)
print(array12 * 2)
print(array12 / 2)
print(array12 + 2)
print(array12 ** 2)
print()

print(array12)
array13 = np.arange(10, 20)
print(array13)
print(array12 + array13)
print(array12 * array13)
print(array12 / array13)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 2  3  4  5  6  7  8  9 10 11]
[ 0  1  4  9 16 25 36 49 64 81]

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]


In [21]:
array14 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array14 > 4)
print(array14 % 2 == 0)
print()

# where = get index of True
booleans = np.array([True, True, False, False, True, False])
print(np.where(booleans))

filter = np.where(array14 > 4)
print(filter)
print(array14[filter])
print(array14[array14 > 4])

[False False  True  True  True  True  True  True  True  True  True]
[ True False False False False False False False False False False]

(array([0, 1, 4]),)
(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)
[ 5  7 11 13 17 19 23 29 31]
[ 5  7 11 13 17 19 23 29 31]


In [22]:
array15 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array15.max())
print(array15.min())
print(array15.mean())
print(np.median(array15))
print(array15.std())
print(array15.var())

31
5
15.25
13.5
8.496322733983215
72.1875
